sources:
  - name: SpaceX
    handler:
      graphql:
        endpoint: https://api.spacex.land/graphql/
  - name: RickandMorty
    handler:
      graphql:
        endpoint: https://rickandmortyapi.com/graphql

